### PR TITLE
Converted the repository into a UPM friendly package

### PR DESCRIPTION
**Pull request by sasvdw**
This is a first stab at converting the repository to a UPM friendly repository that can be added as a package as is explained in [this forum post](https://forum.unity.com/threads/git-support-on-package-manager.573673/)

I've noticed that if the repository information in the `package.json` file doesn't match the url used in UPM when editing your project's `manifest.json` file it fails to retrieve the package. I've created a test branch on this repository I've made the changes on and tested that resolving the package works. Rider is still freaking out a little stating that it couldn't resolve the package, but the files had been downloaded to my project's `Library` folder and I was able to reference the types contained.

### CODE REVIEW

**Comment by jacksondunstan** [comment]
Thank you for the submission! I'll review it soon.

One quick question off the bat: does `PerformanceTests` really need to be under a directly named `Samples~`?

**Comment by sasvdw** [comment]
From what I could see Performance Tests weren't a suit of tests, but rather a sample that could be opened to see the comparison as listed on your website. Including it in the `Samples~` folder means it's ignored at compile time, but allows UPM to import it into a project.

If the performance tests were to be converted to a test suite that could be run by the test runner a dependency on the [Performance testing API](https://docs.unity3d.com/Packages/com.unity.test-framework.performance@1.2/manual/index.html). While I think it might be possible to specify optional dependencies in NPM, I'm not sure if the same support is present in UPM. This was why I rather opted to make the `PerformanceTests` a sample that can be imported.

I do realise that I should have added a section in the `README.md` file that mentions the sample requires the project to add the Perfromance testing API as a package.

**Comment by jacksondunstan** [comment]
Thanks for the info about the samples. My question was more about the naming. Does that directory need to be named specifically `Samples~`?

Most of the changes in the PR look fine, but I've run into issues specifically with the `manifest.json` line to add. In your `README.md`, you have this line:

```json
"com.jacksondunstan.native-collections": "git@github.com:jacksondunstan/NativeCollections.git"
```

When I use that line, with your GitHub since it's not yet in mine, I get this error message in Unity 2019.2 when opening the project:

```
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.jacksondunstan.native-collections: Version 'git@github.com:LazyGameDevZA/NativeCollections.git' is invalid. Expected one of: a 'SemVer' compatible value; a value starting with 'file:'; a Git URL starting with 'git:' or 'git+', or ending with '.git'.
```

If I change it to this:

```json
"com.jacksondunstan.native-collections": "https://github.com/LazyGameDevZA/NativeCollections.git"
```

Then it succeeds with the import and adds this section to the bottom of the file:

```json
"lock": {
  "com.jacksondunstan.native-collections": {
    "hash": "baa7de687be6161530de8e7e00eba3e16034329d",
    "revision": "HEAD"
  }
}
```

However, I then tried this on Unity 2018.1 and Unity 2018.2 and got this error from both when opening the project:

```
Failed to resolve packages: Manifest /path/to/project/Packages/manifest.json has invalid dependencies:
  Error for package 'com.jacksondunstan.native-collections':
    Version is invalid.  Expected a pattern like 'x.x.x[-prerelease]', got 'https://github.com/LazyGameDevZA/NativeCollections.git' instead..  Please see the Editor.log file for more information.
```

Looking at the Unity 2018.3 [release notes](https://unity3d.com/unity/whats-new/unity-2018.3.0), I see the following:

> Package Manager: Added experimental support for Git package dependencies

The release notes for [Unity 2019.1](https://unity3d.com/unity/whats-new/2019.1.0) and [Unity 2019.2](https://unity3d.com/unity/whats-new/2019.2.0) don't say that this feature is no longer experimental, but the 2019.2 release notes do mention some bug fixes related to Git support.

So it seems that the package structure will only work for users on Unity 2018.3 or later and only experimentally for them. Dropping support for 2018.1 and 2018.2 isn't acceptable at this point, so we'll need to find a way to support users on those versions.

I wonder- is there a way of combining both approaches? For example, can `Runtime` be renamed to `JacksonDunstanNativeCollections` so users on 2018.1 or 2018.2 can either follow the old installation procedure of copying that directory into their `Assets` or follow the new UPM-based installation procedure on 2018.3+ (or later to avoid experimental features)?

**Comment by sasvdw** [comment]
You're raising some valid points that I'll explain a little more on below:

The directory naming of `Samples~` allows for Unity to not include the directory when compiling the package. This merely limits the package from including the contained code as part of the base package. I'm struggling to find the documentation that stated the requirement for the `~` character, but ultimately it's the trade-off to consider with how the samples related to the package. Ultimately I feel it's your call if you want to move away from the `Samples~` directory.

Another option to address the `Samples~` directory is to just convert them to performance tests that can be run from the editor, but I"m not sure if your intent was to have them as tests that can be run or as samples to look at.

I seem to have missed that SCP syntax support is a little sketchy for UPM and it's something I'll make sure to address. There URL should be `ssh://git@github.com/jacksondunstan/NativeCollections.git`, but I'll include both the SSH and HTTPS variants for adding the the `manifest.json` file.

I made the mistake of only testing on 2018.3 as that was what I had installed and didn't have time to download older versions. I'll be sure to bump the min version listed in the `package.json` file to match the according version of Unity. I do understand the need to keep it working for 2018.1 and 2018.2 and I'm looking into some options for structuring the code so that it can work. One option is to follow this [example](https://www.patreon.com/posts/25070968). Unfortunately it'll require you to "publish" the package after the code has been merged.

The main reason for using the folder `Runtime` was because it's the convention as provide by Unity's documentation. I can definitely diverge from the convention, but I'm not sure if they have specific plans in place that should go alongside the convention in the future.

I'll see if I can squeeze some time in this week to make the changes required. Admittedly I'm starting to wonder if git support for UPM has managed to get far enough for this to be worth it.

**Comment by sasvdw** [comment]
I'm realising this has stagnated quite a bit since I've last touched this. I'm going to close this pull request for now until I can find the time to think about how to do this properly.

I have noticed recently that GitHub recently introduced the ability to self-host NPM packages (of which UPM is a fork), so I'll take some time to investigate the feasibility of this approach and see how I can incorporate it into the existing repository as is.  If it shows promise I'll submit a new PR that can possibly address this.

**Pull request closed without merging**
